workflows:
  default:
    name: Build and Test
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Dependencies
        script: |
          flutter pub get
          pod install --project-directory=ios
      - name: Run Tests
        script: |
          flutter test
      - name: Build iOS App
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
