workflows:
  ios-build:
    name: Build iOS app
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_VERSION: 3.24.0
    scripts:
      - name: Install dependencies
        script: |
          flutter --version
          flutter pub get
          gem install cocoapods
          pod repo update
          pod install --project-directory=ios
      - name: Update Pods
        script: |
          cd ios
          pod deintegrate
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
