workflows:
  ios-build:
    name: Build iOS app
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_VERSION: 3.24.0
    scripts:
      - name: Install dependencies
        script: |
          flutter --version
          flutter pub get
          gem install cocoapods
      - name: Clean and update Pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod cache clean --all
          pod repo update
          pod install
      - name: Clean Flutter build
        script: |
          flutter clean
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
