# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Add other pods here, if needed
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Auth'
  # pod 'Firebase/Storage'
  # pod 'Firebase/Messaging'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
