platform :ios, '13.0'

# CocoaPods analytics
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # Add other pods here

end
