name: Build & Release

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Clean Build
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Gradle
        run: |
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.2-all.zip" > ./android/gradle/wrapper/gradle-wrapper.properties

      - name: Set up Kotlin Version
        run: |
          sed -i '' 's/ext.kotlin_version = .*/ext.kotlin_version = "2.0.10"/' android/build.gradle

      # Removed APK build step
      # - name: Build APK
      #   run: flutter build apk --release -v

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods
        run: pod install
        working-directory: ios

      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r Etqan.ipa Payload

      # Removed APK check step
      # - name: Check if APK exists
      #   run: |
      #     if [ ! -f build/app/outputs/apk/release/app-release.apk ]; then
      #       echo "APK not found!"
      #       exit 1
      #     fi

      - name: Check if IPA exists
        run: |
          if [ ! -f build/ios/iphoneos/Etqan.ipa ]; then
            echo "IPA not found!"
            exit 1
          fi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/Etqan.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
